MIN_NUM_SESSIONS: 8
MIN_TIME_BETWEEN_SESSIONS: 15
MIN_VIDEOS_PER_SESSION: 3
MAX_VIDEOS_PER_SESSION: 8
MIN_TOTAL_VIDEOS: 100
MAX_TOTAL_VIDEOS: 200
LATEST_EVENT: "2024-03-01"
ATTENTION_LEFT: "https://i.postimg.cc/Pq0xXNSx/attention-left.png"
ATTENTION_RIGHT: "https://i.postimg.cc/nrJqL33C/attention-right.png"
ATTENTION_LEFT_RELATIVE_TIME: 0.25
ATTENTION_RIGHT_RELATIVE_TIME: 0.75
UPLOAD_FOLDER: "uploads"